name: Generate Snake

# Controls when the action will run
on:
  # Triggers the workflow every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Generates the snake animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Hmza1112617
          # These colors match your profile's color scheme
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: '#2E97F7'

      # Pushes the changes to a separate branch called 'output'
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
